Console.Writeline("H");
Console.Writeline("e");
Console.Writeline("l");
Console.Writeline("l");
Console.Writeline("o");
Console.Writeline(" ");
Console.Writeline("C");
Console.Writeline("T");
Console.Writeline("Y");
Console.Writeline("!");